### ISSUE TITLE
M1 macs, "did not find node", but want to

### ISSUE THREAD

**Issue by matthewbivins** [kudrykv/alfred-craftdocs#5]
Hello!
I know that node/npm should be installed in the non-silicon directories of usr/local/bin, but if we're trying to use node natively now that homebrew supports it, do you have any suggestions on making your kickass implementation work? Thanks!

**Comment by kudrykv** [comment]
@matthewbivins RealmDB didn't work with Node and M1. Although, it looks that they should have fix it:
https://github.com/realm/realm-js/pull/3722

I'll update the dependencies and release the update. Hopefully, that will work. Fingers crossed!

**Comment by matthewbivins** [comment]
Thank you, sir! No rush, of course, but keep us posted!

**Comment by kudrykv** [comment]
@matthewbivins please try whether it helps.
https://github.com/kudrykv/alfred-craftdocs/releases/download/v0.2.3/Craft_Docs_v0.2.3.alfredworkflow

**Comment by matthewbivins** [comment]
Thank you! Gave the above a try, but unfortunately still getting "Did not find Node". I made sure to delete the older workflow, and made sure that my node/npm was still in /opt/homebrew/bin/npm…but I guess that could be part of the problem, too?

**Comment by kudrykv** [comment]
Uhh. I'll give it another spin. Part of the problem is the path, as you're saying.

**Comment by kudrykv** [comment]
https://github.com/kudrykv/alfred-craftdocs/releases/download/v0.2.4/Craft_Docs_v0.2.4.alfredworkflow

@matthewbivins you'll need to specify the path in variables
![CleanShot 2021-05-25 at 12 00 12](https://user-images.githubusercontent.com/12697803/119470545-1f4be400-bd51-11eb-84ed-1a999a0449ce.png)

**Comment by matthewbivins** [comment]
So close! I've added my $PATHs, run cdinit, all seems well, but any commands then give me a "Please initialize the workflow" (so polite!). I've tried restarting the machine and reinstalling the workflow. Is there a way/place to run "npm init" manually somewhere? Thank you so much for working so hard on this!

**Comment by matthewbivins** [comment]
Update: I've never gotten too deep into Alfred workflows, but did a little digging to find where yours lives, ran "npm install", and that did the trick! I'm up and running again with this M1 Mac…thanks, Vitaliy!

**Comment by kudrykv** [comment]
Thank you for your investigation!
I've indeed missed another place to update. I'm going to update it, so the following initialization if needed wouldn't require manual intervention with the workflow code.

**Comment by ArttuLai** [comment]
Yess! Can confirm it finally works, straight up like you'd expect (so like, downloading the newest version from releases and installing it 😊)

**Comment by kudrykv** [comment]
🎉🎉🎉
