### ISSUE TITLE
Search seems to have stopped working

### ISSUE THREAD

**Issue by mergesort** [kudrykv/alfred-craftdocs#8]
Hi there, thank you so much for the great work on Craft search, I've been enjoying it immensely!

In a recent update the ability to search Craft has seemingly stopped working, and I'm not quite sure why. On the latest version when I type my hotkey (csearch), the option appears, but as soon as I complete the phrase it transforms into a Google search, as if your search isn't recognized. Below are images that demonstrate what happens, turning the Craft search into a regular google search.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/716513/123440904-4b9d8f00-d5a1-11eb-97e8-8561f4485d02.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/716513/123440935-52c49d00-d5a1-11eb-97ad-67a9cb05bb47.png">

Please let me know if any information would be helpful for debugging, happy to help any way I can!

**Comment by kudrykv** [comment]
Uh-oh 😳 I'll look into it. Thank you for reporting the issue!

**Comment by kudrykv** [comment]
I believe I know what's the issue; hopefully I'll make time to look into it today.

**Comment by mergesort** [comment]
Thanks a lot @kudrykv! Really loving using the plugin, almost like an addendum for my brain. 🙂

**Comment by kudrykv** [comment]
Craft got an update. The database that the workflow is using is not there anymore.
I need to investigate it closer; the issue isn't that straightforward as I initially thought.
I'll keep you posted!

**Comment by kudrykv** [comment]
I'm a little perplexed by the latest version and how it stores the data.

I have good news and okay news. The good news is, I have found another place where I can take the data. Even better, that would be SQLite, meaning I'll be able to switch the language, make the workflow lightweight, and likely working faster.

Okay (or bad news up to some extent) is that it would require a rewrite. It requires a rewrite anyway as to me the database changed from Realm to SQLite.

I've contacted the Craft team; unless they respond how can I get the Realm DB back, then no rewrite would be needed as a right away remedy. If not, this would take a few days.

**Comment by mergesort** [comment]
@kudrykv Well that's good (kind of!). I happened to pop into the Craft Slack and noticed your message and their response showing how to interact with Realm's underpinnings. I'm ok waiting, I understand that you likely have other things to do in your life, and regardless I appreciate the investigation and work you're doing.

**Comment by kudrykv** [comment]
@mergesort their first response was outdated.
Please check [the updated version of the workflow](https://github.com/kudrykv/alfred-craftdocs/releases/download/v0.2.6/Craft_Docs_v0.2.6.alfredworkflow)!

**Comment by mergesort** [comment]
@kudrykv Things are working again, that fixed it! Thanks so much for everything, I'm happy to give you a gold star but is there some other way I can tip you for your hard work or say thank you? 🙂 (Maybe if you throw a sponsor button on the repo, I don't see one on your profile.)

**Comment by kudrykv** [comment]
That's really nice of you 😊 I need to look into sponsor buttons.
I guess come the next time something breaks 😅 , and I expect that won't be soon!

**Comment by mergesort** [comment]
Well if you end up not wanting to wait you know where to find me. Thanks again! 🙂

**Comment by kudrykv** [comment]
@mergesort you may want to try out the other workflow https://github.com/kudrykv/alfred-craftdocs-searchindex
It should work faster than the current one and have smaller memory footprint

**Comment by mergesort** [comment]
Might be worth an issue on that repo, but it doesn't seem to work. When I try to run `cs` I get this pop up.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/716513/125016742-d5d50100-e03f-11eb-9250-244037c0081a.png">

**Comment by kudrykv** [comment]
@mergesort You need to allow to run the executable

**Comment by mergesort** [comment]
Ah of course, not sure how I missed that. 🤦🏻‍♂️

Thanks again, it's working great now!
